### ISSUE TITLE
Cannot deploy to AWS

### ISSUE THREAD

**Issue by abdusco** [bounswe/bounswe2018group10#72]
For some reason unbeknownst to mankind, AWS does not allow me to deploy another instance. I'll try using Heroku instead

**Comment by abdusco** [comment]
Thank god 🙏
The process is much easier with Heroku.

Here's the link:
https://twitter-what-happened.herokuapp.com/

I'll summarize what you need to do:

- Install `gunicorn` with `pip install gunicorn`
- Create a file named `Procfile` and put this in:
    ```text
    web: gunicorn app:app
    ```

    - Here `web:` denotes that we want to create a `web` dyno (which runs the code).
    - `gunicorn` is the command that gets runned
    - `app:app` first the file name without `.py` extension
      the second `app` is name of the variable inside that file that `.run()` method will be called on
- Run `pip freeze > requirements.txt`
- Commit changes
- Go to heroku.com, create an account, and also a new app
- Download [heroku cli][heroku_cli]
- Follow the directions on _Deploy_ tab there to set up git remote for heroku deployment
- Push the code to `heroku` remote

[heroku_cli]: https://devcenter.heroku.com/articles/heroku-cli

**Comment by barisesmer** [comment]
Should we close this issue now, since the problem is resolved ? Maybe we should consider adding this to our wiki page ?

**Comment by abdusco** [comment]
Still working on it, I'm still getting `Unauthorized` errors from Twitter. I'll try generating new tokens

**Comment by abdusco** [comment]
Ah, the problem was that I made a typo when setting up environment variables. It's all fixed now. Check it out at: https://twitter-what-happened.herokuapp.com/

**Comment by alimturkmen** [comment]
Nice, thanks Abdus :)
